osx_image: xcode7
language: objective-c
matrix:
  fast_finish: true
  include:
    - osx_image: xcode7.3
      env:
        - SCHEME="ObjectiveGit Mac"
    - osx_image: xcode7.3
      env:
        - SCHEME="ObjectiveGit iOS"
before_install:
  - gem install xcpretty
  - gem install xcpretty-travis-formatter
install: script/bootstrap
script: script/cibuild
notifications:
  email: false
